name: Run Playwright and Generate a video, screenshots, and LightHouse HTML Report

on:
  push:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev         
          npm ci
          npx playwright install chromium
          npx playwright install webkit
          npm install -g lighthouse chrome-launcher axe-core chromium wait-on
          npm install next@latest
          sudo apt-get install -y libvpx6 libevent-2.1-7 libopus0 libwoff1 libharfbuzz-icu0 libgstallocators-1.0-0 libgstapp-1.0-0 libgstpbutils-1.0-0 libgstaudio-1.0-0 libgsttag-1.0-0 libgstvideo-1.0-0 libgstgl-1.0-0 libgstfft-1.0-0 libhyphen0 libmanette-0.2-0 libflite1 libflite-usenglish1 libflite-cmulex1 libflite-cmu-us-awb1 libflite-cmu-us-kal1 libflite-cmu-us-rms1 libflite-cmu-us-slt1 libgles2

      - name: Create the build
        run: npm run build

      - name: Check and kill process on port 3000
        run: |
          sudo fuser -k 3000/tcp || true

      - name: Start the application
        run: |
          export DISPLAY=:1
          echo "Starting the application..."
          npm run start & npx wait-on --timeout 50000 http://0.0.0.0:3000/
          echo "Application started."

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js

      - name: Generate Lighthouse Report
        run: |
          lighthouse http://localhost:3000 --output html --output-path ./test-results/report.html --chrome-flags="--headless --no-sandbox --disable-gpu"

      - name: Upload report, screenshots and videos of failed tests
        uses: actions/upload-artifact@v3
        with:
          name: ihi
          path: ./ihi